# Generated by Django 5.0.6 on 2024-05-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='update',
            new_name='updated',
        ),
    ]
